name = "gov-programs-ingest"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "gov-programs-ingest-prod"

[env.staging]
name = "gov-programs-ingest-staging"

[[d1_databases]]
binding = "DB"
database_name = "gov-programs-db"
database_id = "placeholder-database-id"

# Schedule: Run every day at 2 AM UTC
[triggers]
crons = ["0 2 * * *"]

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"