name = "gov-programs-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "gov-programs-api-prod"

[env.staging]  
name = "gov-programs-api-staging"

[[d1_databases]]
binding = "DB"
database_name = "gov-programs-db"
database_id = "placeholder-database-id"

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"