name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Typecheck
        run: bun run typecheck
      - name: Tests
        run: bun test
  ops_snapshot:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Generate ops snapshot
        run: bunx tsx scripts/ops.snapshot.ts
      - name: Upload ops snapshot
        uses: actions/upload-artifact@v3
        with:
          name: ops-snapshot
          path: /mnt/data/ops-snapshot.json
