name: deploy

on:
  workflow_dispatch:
    inputs:
      bun-version:
        description: Bun version to install before deployment
        required: false
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUN_VERSION: ${{ inputs.bun-version != '' && inputs.bun-version || 'latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: bunx wrangler deploy
